### ISSUE TITLE
A Qt system tray app should not be the suggested install route

### ISSUE THREAD

**Issue by cunidev** [ActivityWatch/docs#26]
These are my main points:

- at least 50% of Linux users, especially "vanilla" distro ones/newcomers, are using GNOME, which does not (sadly) support system trays anymore.
- it forces users to have an extremely heavy dependency for little practical utility: as Linux is not Windows, it could well be running in background as a service/daemon the whole time for most users, who would still know how to properly start and stop it.
- any UI toolkit should be fully detached from the back-end part by default, and suggesting a Qt "tray" UI as default for Linux users somewhat breaks this rule

Instead, providing instructions on creating a .desktop file (or including it) that simply starts the background daemon (like `libinput-gestures` does) would be a much cleaner approach.

**Comment by ErikBjare** [comment]
That the GNOME team decided to break an API that's available on virtually
every platform is on them. We (me and Johan) have decided to not do
anything about this, but if a GNOME user contributes a GNOME-friendly
solution we'd gladly accept it.

Most of our users are not using Linux, and most people reading the getting
started guide are likely to want the aw-qt manager since it's by far the
easiest way to start using ActivityWatch.

I'm not sure what you mean when you imply that aw-qt is not detached (or
rather, decoupled) from the "backend". It's literally just a small tray
that manages the back-end processes that can be run fully independent of
aw-qt.

**Comment by johan-bjareholt** [comment]
It's not hard to get aw-server running as a systemd daemon (we even supply systemd service files for that, it's also what I personally use).

For the watchers however that's a bit trickier as they can only be run with an X session context, so they have to start when X has started. Something like this might work, but I haven't tested it
https://superuser.com/a/1128905

**Comment by cunidev** [comment]
The simplest solution I found for gnome-shell does not require Qt or similar things.

I've simply created two files, `start.sh` and `kill.sh`, that couldn't be simpler:

`start.sh`:

```
#!/bin/bash

./activitywatch/aw-server &
./activitywatch/aw-watcher-afk & 
./activitywatch/aw-watcher-window [--exclude-title?] &
```

`kill.sh`:

```
#!/bin/bash

pkill aw-
```

**Comment by ErikBjare** [comment]
Those that don't want to use the tray icon could do something like that, yes.

But as I said before, it won't become the default since the UX of it is terrible.

**Comment by cunidev** [comment]
Sure. My main question was: could something like this be added to the documentation as an install option for GNOME users?

**Comment by johan-bjareholt** [comment]
Sure, the docs already mentions Gnome 3 so you could change that text with something pointing to a section of the docs on how to run it easily on Gnome 3.

https://activitywatch.readthedocs.io/en/latest/getting-started.html#usage

**Comment by ErikBjare** [comment]
Your PR (https://github.com/ActivityWatch/docs/pull/28) was merged. Closing.
