### ISSUE TITLE
Better developer documentation

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/docs#3]
- [x] Document event structure
- [x] Document heartbeats
- [x] Document buckets
- [x] Explain bucket bucket name convention
- [x] Explain eventtype name convention
- [x] Document where the peewedb is stored

From https://github.com/ActivityWatch/activitywatch/issues/131#issuecomment-343716590

**Comment by eayoungs** [comment]
I'd really like to know the unit of the 'duration' field, for starters. I assume it's seconds but I can't find it in the docs. I'd be happy to update the docs, if I get confirmation. Thanks!

**Comment by johan-bjareholt** [comment]
@eayoungs In the JSON api it's as simple as a float of seconds and in the python APIs it's a timedelta object. It's really a shame that we have not documented such a basic thing.

**Comment by eayoungs** [comment]
Ah, I guess I missed that; thanks!

**Comment by eayoungs** [comment]
Is there a documentation guide? It might be nice to follow the structure of some other similar but more established projects so that the layout is familiar to new users.

**Comment by ErikBjare** [comment]
@eayoungs Glad you found it!

Yeah, the docs are in a really early stage. I've taken some inspiration from the Syncthing docs (which I guess we could do a better job of emulating) but as of right now our focus is on other parts than the docs. 

We're glad to fix any issues readers let us know of, but a restructuring isn't really on the roadmap right now since large parts of the documentation are rarely read. If you have the time, we'll gladly accept any PRs you might send our way 🙂

**Comment by Sasorien** [comment]
Hey, i have a suggestion :)
Can you update the changelog pls?
Versions v0.8.0b9 and v0.8.1 are missing :( 

https://activitywatch.readthedocs.io/en/latest/changelog.html : `Changelog incomplete`

**Comment by ErikBjare** [comment]
@Sasorien I added some just a few hours ago but apparently forgot to push, it should be live in a short while :)

**Comment by Sasorien** [comment]
Perfect! thx :)
