### ISSUE TITLE
It's not clear how to install aw-client.

### ISSUE THREAD

**Issue by ResourceHog** [ActivityWatch/docs#41]
`pip install aw-client` does not work.

> Could not find a version that satisfies the requirement aw-client

I tried searching for the package here: 
https://pypi.org/search/?q=aw-client
As you can see at the time of this issues creation there is no aw-client package on pypi.

**Comment by johan-bjareholt** [comment]
Inside the aw-client there's both a standard python pyproject.toml file and a Makefile.

As there's a pyproject.toml file you can install it by using `pip install .` or `poetry install` as is standard practice in python projects. You can also install it without cloning it with `pip install git+https://github.com/ActivityWatch/aw-client.git`

You can also see that that's exactly how it's done in the Makefile as well.

We have not published it on pypi because 3rd party watchers have written their own clients instead of re-using aw-client and publishing it would mean more maintenance for us. We might in the future however, but we just see no use for it right now.

**Comment by johan-bjareholt** [comment]
I am now adding proper install instructions to the README files in aw-client and aw-core, possibly more of the other aw projects soon as well.

https://github.com/ActivityWatch/aw-client/pull/49
https://github.com/ActivityWatch/aw-core/pull/90
